<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>RocketComponents</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="RocketComponents.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Falco.Datastar\Falco.Datastar.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <_ContentIncludedByDefault Remove="Properties\launchSettings.json" />
  </ItemGroup>
</Project>
